<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Air Pollution Mortality Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Air_Pollution_on_Mortality_files/libs/clipboard/clipboard.min.js"></script>
<script src="Air_Pollution_on_Mortality_files/libs/quarto-html/quarto.js"></script>
<script src="Air_Pollution_on_Mortality_files/libs/quarto-html/popper.min.js"></script>
<script src="Air_Pollution_on_Mortality_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Air_Pollution_on_Mortality_files/libs/quarto-html/anchor.min.js"></script>
<link href="Air_Pollution_on_Mortality_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Air_Pollution_on_Mortality_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Air_Pollution_on_Mortality_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Air_Pollution_on_Mortality_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Air_Pollution_on_Mortality_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Air Pollution Mortality Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="import-required-libraries" class="level1">
<h1>Import Required Libraries</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hrbrthemes)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PulmoDataSets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-data" class="level1">
<h1>Import Data</h1>
<p>This data contains information from an early study exploring the relationship between air pollution and mortality across 5 Standard Metropolitan Statistical Areas in the U.S. between 1959 and 1961.</p>
<p>Check <a href="https://lightbluetitan.github.io/pulmodatasets/index.html" class="uri">https://lightbluetitan.github.io/pulmodatasets/index.html</a> for more information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"air_polution_mortality_df"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> air_polution_mortality_df</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                City    Mort Precip Educ NonWhite NOX SO2
1       San Jose, CA  790.73     13 12.2      3.0  32   3
2        Wichita, KS  823.76     28 12.1      7.5   2   1
3      San Diego, CA  839.71     10 12.1      5.9  66  20
4      Lancaster, PA  844.05     43  9.5      2.9   7  32
5    Minneapolis, MN  857.62     25 12.1      2.0  11  26
6         Dallas, TX  860.10     35 11.8     14.8   1   1
7          Miami, FL  861.44     60 11.5     13.5   1   1
8    Los Angeles, CA  861.83     11 12.1      7.8 319 130
9   Grand Rapids, MI  871.34     31 10.9      5.1   3  10
10        Denver, CO  871.77     15 12.2      4.7   8  28
11     Rochester, NY  874.28     32 11.1      5.0   4  18
12      Hartford, CT  887.47     43 11.5      7.2   3  10
13    Fort Worth, TX  891.71     31 11.4     11.5   1   1
14      Portland, OR  893.99     37 12.0      3.6  21  44
15     Worcester, MA  895.70     45 11.1      1.0   3   8
16       Seattle, WA  899.26     35 12.2      5.7   7  20
17    Bridgeport, CT  899.53     45 10.6      5.3   4   4
18   Springfield, MA  904.16     45 11.1      3.4   4  20
19 San Francisco, CA  911.70     18 12.2     13.7 171  86
20          York, PA  911.82     42  9.0      4.8   8  49
21         Utica, NY  912.20     40 10.3      2.5   2  11
22        Canton, OH  912.35     36 10.7      6.7   7  20
23   Kansas City, MO  919.73     35 12.0     12.6   4   4
24         Akron, OH  921.87     36 11.4      8.8  15  59
25     New Haven, CT  923.23     46 11.3      8.8   3   8
26     Milwaukee, WI  929.15     30 11.1      5.8  23 125
27        Boston, MA  934.70     43 12.1      3.5  32  62
28        Dayton, OH  936.23     36 11.4     12.4   4  16
29    Providence, RI  938.50     42 10.1      2.2   4  18
30         Flint, MI  941.18     30 10.8     13.1   4  11
31       Reading, PA  946.18     41  9.6      2.7  11  89
32      Syracuse, NY  950.67     38 11.4      3.8   5  25
33       Houston, TX  952.53     46 11.4     21.0   5   1
34   Saint Louis, MO  953.56     34  9.7     17.2  15  68
35    Youngstown, OH  954.44     38 10.7     11.7  13  39
36      Columbus, OH  958.84     37 11.9     13.1   9  15
37       Detroit, MI  959.22     31 10.8     15.8  35 124
38     Nashville, TN  961.01     45 10.1     21.0  14  78
39     Allentown, PA  962.35     44  9.8      0.8   6  33
40    Washington, DC  967.80     41 12.3     25.9  28 102
41  Indianapolis, IN  968.66     39 11.4     15.6   7  33
42    Cincinnati, OH  970.47     40 10.2     13.0  26 146
43   Greeensboro, NC  971.12     42 10.4     22.7   3   5
44        Toledo, OH  972.46     31 10.7      9.5   7  25
45       Atlanta, GA  982.29     47 11.1     27.1   8  24
46     Cleveland, OH  985.95     35 11.1     14.7  21  64
47    Louisville, KY  989.27     30  9.9     13.1  37 193
48    Pittsburgh, PA  991.29     36 10.6      8.1  59 263
49      New York, NY  994.65     42 10.7     11.3  26 108
50        Albany, NY  997.88     35 11.0      3.5  10  39
51       Buffalo, NY 1001.90     36 10.5      8.1  12  37
52    Wilmington, DE 1003.50     45 11.3     12.1  11  42
53       Memphis, TN 1006.49     50 10.4     36.7  18  34
54  Philadelphia, PA 1015.02     42 10.5     17.5  32 161
55   Chattanooga, TN 1017.61     52  9.6     22.2   8  27
56       Chicago, IL 1024.89     33 10.9     16.3  63 278
57      Richmond, VA 1025.50     44 11.0     28.6   9  48
58    Birmingham, AL 1030.38     53 10.2     38.5  32  72
59     Baltimore, MD 1071.29     43  9.6     24.4  38 206
60   New Orleans, LA 1113.06     54  9.7     31.4  17   1</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>Exploratory Data Analysis</h1>
<p>I assume that <em>City</em> won’t be necessary and dropped in this stage since it is a unique and a categorical/factor variable. However, as each city has its non-unique states, it will still be considered later.</p>
<section id="quick-summary" class="level2">
<h2 class="anchored" data-anchor-id="quick-summary">Quick Summary</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df_num <span class="ot">&lt;-</span> df[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(df_num)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">df_num</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mort</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">940.36</td>
<td style="text-align: right;">62.20</td>
<td style="text-align: right;">790.73</td>
<td style="text-align: right;">898.37</td>
<td style="text-align: right;">943.68</td>
<td style="text-align: right;">983.20</td>
<td style="text-align: right;">1113.06</td>
<td style="text-align: left;">&lt;U+2582&gt;&lt;U+2586&gt;&lt;U+2587&gt;&lt;U+2585&gt;&lt;U+2581&gt;</td>
</tr>
<tr class="even">
<td style="text-align: left;">Precip</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">37.37</td>
<td style="text-align: right;">9.98</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">32.75</td>
<td style="text-align: right;">38.00</td>
<td style="text-align: right;">43.25</td>
<td style="text-align: right;">60.00</td>
<td style="text-align: left;">&lt;U+2582&gt;&lt;U+2582&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2581&gt;</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educ</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.97</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: right;">11.05</td>
<td style="text-align: right;">11.50</td>
<td style="text-align: right;">12.30</td>
<td style="text-align: left;">&lt;U+2582&gt;&lt;U+2583&gt;&lt;U+2586&gt;&lt;U+2587&gt;&lt;U+2586&gt;</td>
</tr>
<tr class="even">
<td style="text-align: left;">NonWhite</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11.87</td>
<td style="text-align: right;">8.92</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: right;">15.65</td>
<td style="text-align: right;">38.50</td>
<td style="text-align: left;">&lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2582&gt;&lt;U+2581&gt;&lt;U+2581&gt;</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NOX</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22.65</td>
<td style="text-align: right;">46.33</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">23.75</td>
<td style="text-align: right;">319.00</td>
<td style="text-align: left;">&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;</td>
</tr>
<tr class="even">
<td style="text-align: left;">SO2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">53.77</td>
<td style="text-align: right;">63.39</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">69.00</td>
<td style="text-align: right;">278.00</td>
<td style="text-align: left;">&lt;U+2587&gt;&lt;U+2582&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="histogram" class="level2">
<h2 class="anchored" data-anchor-id="histogram">Histogram</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> <span class="fu">colnames</span>(df_num)){</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hist</span>(df_num[[col]], <span class="at">freq =</span> F, <span class="at">breaks =</span> <span class="dv">13</span>, <span class="at">xlab =</span> col, <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">'Dist of'</span>, col), <span class="at">col =</span> <span class="st">'lightblue'</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="fu">density</span>(df_num[[col]]), <span class="at">col =</span> <span class="st">'blue'</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Each variable’s, except for <em>NOX</em>, distribution seems quite reasonable and satisfies the assumption of a regression that <em>There must be sufficient variation in the values of X variables</em>. Although <em>SO2</em> appears to be heavily skewed, its values still vary between 50-250. NOX, on the other hand, are lies almost entirely between 0 and 50, with only few points outside of this range.</p>
<p>I suppose that <em>NOX</em> won’t give significant effect in the model. But we’ll see.</p>
</section>
<section id="scatter-plot" class="level2">
<h2 class="anchored" data-anchor-id="scatter-plot">Scatter Plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(df_num,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">'blue'</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">gap =</span> <span class="dv">0</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is apparent that the effect of <em>NOX</em> on <em>Mort</em> appears to be completely random – might still be slightly correlated though.</p>
<p>This graph gives me a suspicion of nonlinear link between <em>SO2</em> and <em>City</em>. I will perform a certain transformation on the variable to reveal this nonlinear relationship.</p>
</section>
<section id="correlation-heatmap" class="level2">
<h2 class="anchored" data-anchor-id="correlation-heatmap">Correlation Heatmap</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> <span class="fu">melt</span>(<span class="fu">cor</span>(df_num, <span class="at">method =</span> <span class="st">"pearson"</span>), <span class="at">as.is =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(corr, <span class="fu">aes</span>(<span class="at">x =</span> X1, <span class="at">y =</span> X2, <span class="at">fill =</span> value)) <span class="sc">+</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">'RdBu'</span>, <span class="at">limit =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(value, <span class="dv">2</span>)), <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Variables Correlation'</span>, <span class="at">x =</span> <span class="st">''</span>, <span class="at">y =</span> <span class="st">''</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As I assumed previously, <em>NOX</em> is barely correlated with <em>Mort</em>, with only -0.08 of correlation coefficient. I also thought of a nonlinear correlation between <em>SO2</em> and <em>Mort</em>. To capture their connection more accurately, I am considering on using Spearman method to assess it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df_num<span class="sc">$</span>SO2, df_num<span class="sc">$</span>Mort, <span class="at">method =</span> <span class="st">'spearman'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4905252</code></pre>
</div>
</div>
<p>Apparently, It doesn’t remarkably differ with the Pearson method, yet still give a moderate correlation coefficient.</p>
</section>
</section>
<section id="modeling" class="level1">
<h1>Modeling</h1>
<p>Since the data only contains numeric variables and the dependent variable is a continuous variable, this will be an easy regression analysis. The analysis will be conducted using backward elimination method. I will rely on the statistical test, such as t-test, to eliminate insignificant variables. However, in the later section, I will also consider to retain insignificant variable based on prior evidence and/or domain knowledge.</p>
<section id="first-model" class="level2">
<h2 class="anchored" data-anchor-id="first-model">First Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> ., <span class="at">data =</span> df_num)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ ., data = df_num)

Residuals:
    Min      1Q  Median      3Q     Max 
-91.893 -18.986  -3.433  15.872  91.528 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1000.1026    92.3982  10.824 3.85e-15 ***
Precip         1.3792     0.7000   1.970 0.053943 .  
Educ         -15.0791     7.0706  -2.133 0.037518 *  
NonWhite       3.1602     0.6287   5.026 5.84e-06 ***
NOX           -0.1076     0.1359  -0.792 0.432030    
SO2            0.3554     0.0914   3.889 0.000278 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 37.36 on 54 degrees of freedom
Multiple R-squared:  0.6698,    Adjusted R-squared:  0.6392 
F-statistic:  21.9 on 5 and 54 DF,  p-value: 6.478e-12</code></pre>
</div>
</div>
<p>A pretty decent starting model, with the R-squared value of 0.6392. Next, I will transform <em>SO2</em> with <em>log</em> transformation to reveal the nonlinear effect.</p>
</section>
<section id="second-model" class="level2">
<h2 class="anchored" data-anchor-id="second-model">Second Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> Educ <span class="sc">+</span> NonWhite <span class="sc">+</span> NOX <span class="sc">+</span> <span class="fu">log</span>(SO2), <span class="at">data =</span> df_num)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + Educ + NonWhite + NOX + log(SO2), 
    data = df_num)

Residuals:
    Min      1Q  Median      3Q     Max 
-98.988 -19.940   1.057  17.499 115.431 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 944.17471   94.17758  10.025 6.25e-14 ***
Precip        1.42242    0.68221   2.085   0.0418 *  
Educ        -13.35817    6.95943  -1.919   0.0602 .  
NonWhite      3.43512    0.60693   5.660 5.95e-07 ***
NOX          -0.09677    0.12989  -0.745   0.4595    
log(SO2)     15.96124    3.67450   4.344 6.21e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 36.39 on 54 degrees of freedom
Multiple R-squared:  0.6867,    Adjusted R-squared:  0.6577 
F-statistic: 23.68 on 5 and 54 DF,  p-value: 1.615e-12</code></pre>
</div>
</div>
<p>It can be seen that <em>log SO2</em> results in a higher coefficient and higher Adjusted R-squared of the model. From this point onward, I will use <em>log SO2</em> in the model.</p>
</section>
<section id="third-model" class="level2">
<h2 class="anchored" data-anchor-id="third-model">Third Model</h2>
<p>To give a better perspective on how each variable influences the dependent variable, I transform the variables to a standardised form. Standardisation on regression is basically the same as regular regression with a transformation of <em>k = 1/var(X)</em>. Hence, by its statistical properties, the R-squared remain the same as the regular form, but with a better interpretation of the <em>beta</em> coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df_num<span class="sc">$</span>log_SO2 <span class="ot">&lt;-</span> <span class="fu">log</span>(df_num<span class="sc">$</span>SO2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df_scaled2 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(df_num))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>df_scaled2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df_scaled2, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(SO2))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>model_scaled<span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> Educ <span class="sc">+</span> NonWhite <span class="sc">+</span> NOX <span class="sc">+</span> log_SO2, <span class="at">data =</span> df_scaled2)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_scaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + Educ + NonWhite + NOX + log_SO2, 
    data = df_scaled2)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.59140 -0.32056  0.01699  0.28132  1.85575 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.767e-16  7.553e-02   0.000   1.0000    
Precip       2.283e-01  1.095e-01   2.085   0.0418 *  
Educ        -1.815e-01  9.458e-02  -1.919   0.0602 .  
NonWhite     4.927e-01  8.705e-02   5.660 5.95e-07 ***
NOX         -7.208e-02  9.676e-02  -0.745   0.4595    
log_SO2      3.843e-01  8.847e-02   4.344 6.21e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.585 on 54 degrees of freedom
Multiple R-squared:  0.6867,    Adjusted R-squared:  0.6577 
F-statistic: 23.68 on 5 and 54 DF,  p-value: 1.615e-12</code></pre>
</div>
</div>
<p>As we can see, the Adjusted R-squared remain consistent while the <em>beta</em> coefficient is transformed. Here, the model shows that <em>NOX</em> has a small influence on <em>Mort</em> by less than 0.1 of. <em>beta</em> coefficient. Therefore, I drop the variable to look for a better fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> Educ <span class="sc">+</span> NonWhite <span class="sc">+</span> log_SO2, <span class="at">data =</span> df_scaled2)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + Educ + NonWhite + log_SO2, data = df_scaled2)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.61353 -0.36244 -0.01152  0.30893  1.78077 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.881e-16  7.522e-02   0.000  1.00000    
Precip       2.634e-01  9.847e-02   2.675  0.00982 ** 
Educ        -1.898e-01  9.355e-02  -2.028  0.04736 *  
NonWhite     4.763e-01  8.390e-02   5.678 5.31e-07 ***
log_SO2      3.615e-01  8.266e-02   4.373 5.50e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5827 on 55 degrees of freedom
Multiple R-squared:  0.6835,    Adjusted R-squared:  0.6605 
F-statistic:  29.7 on 4 and 55 DF,  p-value: 3.599e-13</code></pre>
</div>
</div>
<p>Dropping <em>NOX</em> apparently leads to a better fit of the model – shown by bigger Adjusted R-Squared.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model_unscaled <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> Educ <span class="sc">+</span> NonWhite <span class="sc">+</span> <span class="fu">log</span>(SO2), <span class="at">data =</span> df_num)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + Educ + NonWhite + log(SO2), data = df_num)

Residuals:
     Min       1Q   Median       3Q      Max 
-100.364  -22.544   -0.716   19.216  110.767 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 944.8448    93.7916  10.074 4.28e-14 ***
Precip        1.6410     0.6134   2.675  0.00982 ** 
Educ        -13.9637     6.8838  -2.028  0.04736 *  
NonWhite      3.3212     0.5850   5.678 5.31e-07 ***
log(SO2)     15.0134     3.4333   4.373 5.50e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 36.24 on 55 degrees of freedom
Multiple R-squared:  0.6835,    Adjusted R-squared:  0.6605 
F-statistic:  29.7 on 4 and 55 DF,  p-value: 3.599e-13</code></pre>
</div>
</div>
<p>Moreover, All of the variables satisfy the significance requirement (<em>beta ≠ 0</em>), as reflected by p-values &lt; 0.05.</p>
</section>
</section>
<section id="dummy-modeling" class="level1">
<h1>Dummy Modeling</h1>
<p>An Adjusted R-Squared of 0.6605 is quite acceptable, but I think it could be improved.</p>
<p>In the previous stage, I didn’t consider <em>City</em> as an explanatory variable as it is a unique factor. However, some cities shared same States that could be regarded as a covariate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Location <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">".*,</span><span class="sc">\\</span><span class="st">s*"</span>, <span class="st">""</span>, df<span class="sc">$</span>City)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(City))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Mort Precip Educ NonWhite NOX SO2 Location
1   790.73     13 12.2      3.0  32   3       CA
2   823.76     28 12.1      7.5   2   1       KS
3   839.71     10 12.1      5.9  66  20       CA
4   844.05     43  9.5      2.9   7  32       PA
5   857.62     25 12.1      2.0  11  26       MN
6   860.10     35 11.8     14.8   1   1       TX
7   861.44     60 11.5     13.5   1   1       FL
8   861.83     11 12.1      7.8 319 130       CA
9   871.34     31 10.9      5.1   3  10       MI
10  871.77     15 12.2      4.7   8  28       CO
11  874.28     32 11.1      5.0   4  18       NY
12  887.47     43 11.5      7.2   3  10       CT
13  891.71     31 11.4     11.5   1   1       TX
14  893.99     37 12.0      3.6  21  44       OR
15  895.70     45 11.1      1.0   3   8       MA
16  899.26     35 12.2      5.7   7  20       WA
17  899.53     45 10.6      5.3   4   4       CT
18  904.16     45 11.1      3.4   4  20       MA
19  911.70     18 12.2     13.7 171  86       CA
20  911.82     42  9.0      4.8   8  49       PA
21  912.20     40 10.3      2.5   2  11       NY
22  912.35     36 10.7      6.7   7  20       OH
23  919.73     35 12.0     12.6   4   4       MO
24  921.87     36 11.4      8.8  15  59       OH
25  923.23     46 11.3      8.8   3   8       CT
26  929.15     30 11.1      5.8  23 125       WI
27  934.70     43 12.1      3.5  32  62       MA
28  936.23     36 11.4     12.4   4  16       OH
29  938.50     42 10.1      2.2   4  18       RI
30  941.18     30 10.8     13.1   4  11       MI
31  946.18     41  9.6      2.7  11  89       PA
32  950.67     38 11.4      3.8   5  25       NY
33  952.53     46 11.4     21.0   5   1       TX
34  953.56     34  9.7     17.2  15  68       MO
35  954.44     38 10.7     11.7  13  39       OH
36  958.84     37 11.9     13.1   9  15       OH
37  959.22     31 10.8     15.8  35 124       MI
38  961.01     45 10.1     21.0  14  78       TN
39  962.35     44  9.8      0.8   6  33       PA
40  967.80     41 12.3     25.9  28 102       DC
41  968.66     39 11.4     15.6   7  33       IN
42  970.47     40 10.2     13.0  26 146       OH
43  971.12     42 10.4     22.7   3   5       NC
44  972.46     31 10.7      9.5   7  25       OH
45  982.29     47 11.1     27.1   8  24       GA
46  985.95     35 11.1     14.7  21  64       OH
47  989.27     30  9.9     13.1  37 193       KY
48  991.29     36 10.6      8.1  59 263       PA
49  994.65     42 10.7     11.3  26 108       NY
50  997.88     35 11.0      3.5  10  39       NY
51 1001.90     36 10.5      8.1  12  37       NY
52 1003.50     45 11.3     12.1  11  42       DE
53 1006.49     50 10.4     36.7  18  34       TN
54 1015.02     42 10.5     17.5  32 161       PA
55 1017.61     52  9.6     22.2   8  27       TN
56 1024.89     33 10.9     16.3  63 278       IL
57 1025.50     44 11.0     28.6   9  48       VA
58 1030.38     53 10.2     38.5  32  72       AL
59 1071.29     43  9.6     24.4  38 206       MD
60 1113.06     54  9.7     31.4  17   1       LA</code></pre>
</div>
</div>
<section id="quick-eda" class="level2">
<h2 class="anchored" data-anchor-id="quick-eda">Quick EDA</h2>
<p>Do different states mean different Mortality Rate?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Location <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">".*,</span><span class="sc">\\</span><span class="st">s*"</span>, <span class="st">""</span>, df<span class="sc">$</span>City)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(City))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>grouped <span class="ot">=</span> df2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Location) <span class="sc">%&gt;%</span> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg =</span> <span class="fu">mean</span>(Mort), <span class="at">Var =</span> <span class="fu">var</span>(Mort))</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> Location, <span class="at">y =</span> Mort)) <span class="sc">+</span> </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">position =</span> <span class="st">'identity'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To ensure that the differences are real, let’s use a statistical test. Although ANOVA is the standard method to evaluate the presence of differences, it assumes the same variance between group, which is not satisfied in this data (some group contain only 1 observation, resulting in NA variance). Thus, I will perform Kruskal-Wallis test as an alternative to ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(Mort <span class="sc">~</span> Location, <span class="at">data =</span> df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Mort by Location
Kruskal-Wallis chi-squared = 42.05, df = 28, p-value = 0.04289</code></pre>
</div>
</div>
<p>The result shows that there is at least one group that differ from the other. Hence, <em>Location</em> might have a significant effect towards <em>Mort.</em></p>
<p>We still have to be aware whether <em>Location</em> also affect, or at least correlated, other explanatory variables or not. I will reveal its effect towards the others later in the multicollinearity test.</p>
</section>
<section id="first-model-1" class="level2">
<h2 class="anchored" data-anchor-id="first-model-1">First Model</h2>
<p>I will continue to use the standardised model to provide a better insight into the true effect of the predictors on the dependent variable. I will also modify the reference category of the categorical variable, using the category with the highest <em>Mort</em> as the reference, to see which states truly differ from it</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_scaled2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_scaled2, df2<span class="sc">$</span>Location)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_scaled2)[<span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="st">'Location'</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>df_scaled2<span class="sc">$</span>Location <span class="ot">&lt;-</span> df_scaled2<span class="sc">$</span>Location <span class="sc">%&gt;%</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relevel</span>(<span class="at">ref =</span> <span class="st">'LA'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Move on to the first model with dummy variable. Since the third model in the latest stage has been proven to be the best model – all variables are statistically significant and generates quiet high Adjusted R-squared – I will start the first dummy model with the corresponding regressors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dummy1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> Educ <span class="sc">+</span> NonWhite <span class="sc">+</span> log_SO2 <span class="sc">+</span> Location, <span class="at">data =</span> df_scaled2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + Educ + NonWhite + log_SO2 + Location, 
    data = df_scaled2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.2125 -0.1368  0.0000  0.1277  0.7939 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  2.13182    0.96259   2.215  0.03541 * 
Precip       0.30615    0.31509   0.972  0.33987   
Educ         0.08694    0.15989   0.544  0.59106   
NonWhite     0.52419    0.24066   2.178  0.03830 * 
log_SO2      0.41309    0.16829   2.455  0.02083 * 
LocationAL  -2.94682    0.84158  -3.502  0.00163 **
LocationCA  -2.73476    1.39852  -1.955  0.06095 . 
LocationCO  -2.29077    1.46662  -1.562  0.12995   
LocationCT  -2.33427    1.02642  -2.274  0.03112 * 
LocationDC  -3.15667    1.09658  -2.879  0.00772 **
LocationDE  -1.54692    1.15217  -1.343  0.19058   
LocationFL  -3.36256    1.07574  -3.126  0.00421 **
LocationGA  -2.65567    0.89660  -2.962  0.00631 **
LocationIL  -1.56206    1.20458  -1.297  0.20569   
LocationIN  -2.07248    1.08085  -1.917  0.06582 . 
LocationKS  -2.69632    1.15044  -2.344  0.02670 * 
LocationKY  -1.65118    1.20713  -1.368  0.18263   
LocationMA  -2.27781    1.22155  -1.865  0.07313 . 
LocationMD  -1.38226    0.99699  -1.386  0.17696   
LocationMI  -2.13829    1.05082  -2.035  0.05179 . 
LocationMN  -2.63550    1.38410  -1.904  0.06760 . 
LocationMO  -2.16018    0.97402  -2.218  0.03517 * 
LocationNC  -1.91873    0.84366  -2.274  0.03111 * 
LocationNY  -1.56797    1.09837  -1.428  0.16489   
LocationOH  -1.98371    1.02249  -1.940  0.06288 . 
LocationOR  -2.64757    1.34663  -1.966  0.05965 . 
LocationPA  -2.03577    1.10138  -1.848  0.07553 . 
LocationRI  -1.56108    1.18443  -1.318  0.19858   
LocationTN  -2.52616    0.77034  -3.279  0.00287 **
LocationTX  -2.16100    0.84678  -2.552  0.01668 * 
LocationVA  -2.13805    0.91811  -2.329  0.02760 * 
LocationWA  -2.42800    1.27640  -1.902  0.06786 . 
LocationWI  -2.19239    1.32599  -1.653  0.10983   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5144 on 27 degrees of freedom
Multiple R-squared:  0.8789,    Adjusted R-squared:  0.7354 
F-statistic: 6.125 on 32 and 27 DF,  p-value: 3.794e-06</code></pre>
</div>
</div>
</section>
<section id="second-model-1" class="level2">
<h2 class="anchored" data-anchor-id="second-model-1">Second Model</h2>
<p>The previous model is generally good, since it improved the Adjusted R-squared from 0.6605 to 0.7354. However, it might still be improved as the model contains many insignificant variables.</p>
<p>In the second model, I drop <em>Educ</em> as it only affect <em>Mort</em> by 0.08 of <em>Mort</em> standard deviation. I also don’t think that Education directly influence a city’s mortality rate. (Might be a bit biased on this :D)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dummy2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> NonWhite <span class="sc">+</span> log_SO2 <span class="sc">+</span> Location, <span class="at">data =</span> df_scaled2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + NonWhite + log_SO2 + Location, data = df_scaled2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.2344 -0.1680  0.0000  0.1775  0.8145 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   1.9394     0.8839   2.194  0.03668 * 
Precip        0.2484     0.2929   0.848  0.40362   
NonWhite      0.5718     0.2213   2.584  0.01527 * 
log_SO2       0.3881     0.1598   2.428  0.02186 * 
LocationAL   -2.8677     0.8184  -3.504  0.00156 **
LocationCA   -2.5369     1.3333  -1.903  0.06740 . 
LocationCO   -2.0611     1.3867  -1.486  0.14837   
LocationCT   -2.0790     0.9012  -2.307  0.02867 * 
LocationDC   -2.8579     0.9370  -3.050  0.00496 **
LocationDE   -1.2690     1.0195  -1.245  0.22356   
LocationFL   -3.0471     0.8944  -3.407  0.00201 **
LocationGA   -2.4762     0.8231  -3.008  0.00550 **
LocationIL   -1.3856     1.1454  -1.210  0.23649   
LocationIN   -1.8417     0.9814  -1.876  0.07105 . 
LocationKS   -2.4723     1.0605  -2.331  0.02717 * 
LocationKY   -1.5839     1.1856  -1.336  0.19231   
LocationMA   -1.9506     1.0496  -1.858  0.07365 . 
LocationMD   -1.3299     0.9798  -1.357  0.18551   
LocationMI   -1.9966     1.0051  -1.986  0.05685 . 
LocationMN   -2.3451     1.2607  -1.860  0.07341 . 
LocationMO   -2.0198     0.9273  -2.178  0.03797 * 
LocationNC   -1.8428     0.8215  -2.243  0.03298 * 
LocationNY   -1.3546     1.0129  -1.337  0.19187   
LocationOH   -1.7848     0.9428  -1.893  0.06871 . 
LocationOR   -2.2977     1.1680  -1.967  0.05914 . 
LocationPA   -1.8881     1.0539  -1.792  0.08401 . 
LocationRI   -1.3852     1.1250  -1.231  0.22846   
LocationTN   -2.4332     0.7416  -3.281  0.00277 **
LocationTX   -1.9854     0.7729  -2.569  0.01582 * 
LocationVA   -1.9827     0.8615  -2.302  0.02901 * 
LocationWA   -2.0935     1.1043  -1.896  0.06834 . 
LocationWI   -1.9700     1.2454  -1.582  0.12492   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5078 on 28 degrees of freedom
Multiple R-squared:  0.8776,    Adjusted R-squared:  0.7421 
F-statistic: 6.476 on 31 and 28 DF,  p-value: 1.646e-06</code></pre>
</div>
</div>
<p>Although the Adjusted R-squared increased, it only rose by barely 0.07</p>
</section>
<section id="third-model-1" class="level2">
<h2 class="anchored" data-anchor-id="third-model-1">Third Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dummy3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> NonWhite <span class="sc">+</span> log_SO2 <span class="sc">+</span> Location, <span class="at">data =</span> df_scaled2)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ NonWhite + log_SO2 + Location, data = df_scaled2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.1850 -0.1499  0.0000  0.1517  0.8600 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   2.1453     0.8458   2.537  0.01684 * 
NonWhite      0.6391     0.2056   3.109  0.00418 **
log_SO2       0.3597     0.1555   2.313  0.02803 * 
LocationAL   -2.8651     0.8144  -3.518  0.00145 **
LocationCA   -3.3137     0.9641  -3.437  0.00180 **
LocationCO   -2.7667     1.1040  -2.506  0.01807 * 
LocationCT   -2.0914     0.8967  -2.332  0.02683 * 
LocationDC   -3.0522     0.9042  -3.376  0.00211 **
LocationDE   -1.2764     1.0145  -1.258  0.21836   
LocationFL   -2.7628     0.8252  -3.348  0.00227 **
LocationGA   -2.5576     0.8135  -3.144  0.00383 **
LocationIL   -1.6874     1.0834  -1.558  0.13018   
LocationIN   -2.0294     0.9515  -2.133  0.04154 * 
LocationKS   -2.9387     0.9023  -3.257  0.00287 **
LocationKY   -1.9432     1.1019  -1.763  0.08837 . 
LocationMA   -1.9160     1.0437  -1.836  0.07667 . 
LocationMD   -1.4498     0.9648  -1.503  0.14375   
LocationMI   -2.3655     0.9017  -2.623  0.01373 * 
LocationMN   -2.7829     1.1445  -2.431  0.02145 * 
LocationMO   -2.3273     0.8493  -2.740  0.01040 * 
LocationNC   -2.0452     0.7823  -2.615  0.01403 * 
LocationNY   -1.5149     0.9903  -1.530  0.13692   
LocationOH   -2.0097     0.9003  -2.232  0.03349 * 
LocationOR   -2.4392     1.1504  -2.120  0.04266 * 
LocationPA   -1.9305     1.0476  -1.843  0.07560 . 
LocationRI   -1.4087     1.1192  -1.259  0.21819   
LocationTN   -2.4510     0.7377  -3.322  0.00242 **
LocationTX   -2.2820     0.6858  -3.328  0.00239 **
LocationVA   -2.1369     0.8379  -2.550  0.01631 * 
LocationWA   -2.3156     1.0676  -2.169  0.03842 * 
LocationWI   -2.2824     1.1838  -1.928  0.06371 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5054 on 29 degrees of freedom
Multiple R-squared:  0.8745,    Adjusted R-squared:  0.7446 
F-statistic: 6.734 on 30 and 29 DF,  p-value: 8.394e-07</code></pre>
</div>
</div>
<p>Lastly, I dropped <em>Precip</em> since it is also statistically insignificant towards the model. By dropping it, the model generates slightly higher Adjusted R-squared.</p>
<p>I think this model is already a good fit, even though some of the dummies are still statistically insignificant.</p>
</section>
</section>
<section id="final-model" class="level1">
<h1>Final Model</h1>
<p>As I stated in the <strong>Modeling</strong> Section, I won’t solely rely on the statistical properties but some domain knowledge as well. I might also consider existing evidences and combine it with the statistical properties.</p>
<p>In this case, I still want to include <em>Precip</em> into the model because some researches have said that precipitation, and heavy rain, do associates with mortality risk and poses health risks.</p>
<p>On the other side, <em>Educ</em> could have been a reasonable variable to be included as well. Several studies have shown a connection between mortality and education, concluding that education is one of the key factor in reducing mortality risk. However, this conclusion isn’t well-reflected in this analysis. In the first dummy model <em>dummy1</em>, <em>Educ</em> has a positive link with <em>Mort</em>, implying that higher median years of education are linked to a higher mortality rate, which is the opposite of the findings from previous research. Therefore, I will not include <em>Educ</em> into the final model</p>
<p>Thus, the second dummy model <em>dummy2</em> would be the final model and will be tested whether it satisfies the classic linear regression assumptions. The model below is the unscaled model, which will be testes afterwards.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Location <span class="ot">&lt;-</span> df2<span class="sc">$</span>Location <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relevel</span>(<span class="at">ref =</span> <span class="st">'LA'</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>dummy_unscaled <span class="ot">&lt;-</span> <span class="fu">lm</span>(Mort <span class="sc">~</span> Precip <span class="sc">+</span> NonWhite <span class="sc">+</span> <span class="fu">log</span>(SO2) <span class="sc">+</span> Location, <span class="at">data =</span> df2)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy_unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Mort ~ Precip + NonWhite + log(SO2) + Location, 
    data = df2)

Residuals:
   Min     1Q Median     3Q    Max 
-76.78 -10.45   0.00  11.04  50.66 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  904.313     98.130   9.215 5.66e-10 ***
Precip         1.547      1.825   0.848  0.40362    
NonWhite       3.987      1.543   2.584  0.01527 *  
log(SO2)      16.119      6.639   2.428  0.02186 *  
LocationAL  -178.378     50.907  -3.504  0.00156 ** 
LocationCA  -157.802     82.932  -1.903  0.06740 .  
LocationCO  -128.204     86.256  -1.486  0.14837    
LocationCT  -129.315     56.056  -2.307  0.02867 *  
LocationDC  -177.768     58.283  -3.050  0.00496 ** 
LocationDE   -78.932     63.415  -1.245  0.22356    
LocationFL  -189.534     55.634  -3.407  0.00201 ** 
LocationGA  -154.023     51.197  -3.008  0.00550 ** 
LocationIL   -86.186     71.243  -1.210  0.23649    
LocationIN  -114.556     61.048  -1.876  0.07105 .  
LocationKS  -153.779     65.966  -2.331  0.02717 *  
LocationKY   -98.523     73.745  -1.336  0.19231    
LocationMA  -121.332     65.288  -1.858  0.07365 .  
LocationMD   -82.722     60.944  -1.357  0.18551    
LocationMI  -124.192     62.520  -1.986  0.05685 .  
LocationMN  -145.867     78.419  -1.860  0.07341 .  
LocationMO  -125.637     57.681  -2.178  0.03797 *  
LocationNC  -114.628     51.099  -2.243  0.03298 *  
LocationNY   -84.259     63.005  -1.337  0.19187    
LocationOH  -111.020     58.641  -1.893  0.06871 .  
LocationOR  -142.923     72.654  -1.967  0.05914 .  
LocationPA  -117.442     65.552  -1.792  0.08401 .  
LocationRI   -86.160     69.975  -1.231  0.22846    
LocationTN  -151.347     46.129  -3.281  0.00277 ** 
LocationTX  -123.494     48.073  -2.569  0.01582 *  
LocationVA  -123.325     53.584  -2.302  0.02901 *  
LocationWA  -130.222     68.688  -1.896  0.06834 .  
LocationWI  -122.535     77.463  -1.582  0.12492    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 31.59 on 28 degrees of freedom
Multiple R-squared:  0.8776,    Adjusted R-squared:  0.7421 
F-statistic: 6.476 on 31 and 28 DF,  p-value: 1.646e-06</code></pre>
</div>
</div>
</section>
<section id="assumptions" class="level1">
<h1>Assumptions</h1>
<section id="linearity" class="level2">
<h2 class="anchored" data-anchor-id="linearity">Linearity</h2>
<p>As the name suggests, Linear Regression is a formula that expresses the conditional expectation of <em>Y</em> as a linear function of <em>X</em>. However, the term “linear” here refers to linearity in the parameters, which allows the transformation of <em>X</em> variables using any of nonlinear function, such as <em>log(SO2)</em> in the prior stages.</p>
<p>This model certainly pass this assumption.</p>
</section>
<section id="exogeneity" class="level2">
<h2 class="anchored" data-anchor-id="exogeneity">Exogeneity</h2>
<p>This assumption states that <em>Covariance, or Correlation, between independent variables and errors should be zero</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>X_resid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Residual =</span> dummy_unscaled<span class="sc">$</span>resid, <span class="at">Precip =</span> df2<span class="sc">$</span>Precip, <span class="at">NonWhite =</span> df2<span class="sc">$</span>NonWhite, <span class="at">log_SO2 =</span> <span class="fu">log</span>(df2<span class="sc">$</span>SO2))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(X_resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Residual        Precip      NonWhite       log_SO2
Residual  1.000000e+00 -2.734472e-17 -3.658546e-17 -4.615482e-17
Precip   -2.734472e-17  1.000000e+00  4.132045e-01 -1.211723e-01
NonWhite -3.658546e-17  4.132045e-01  1.000000e+00  5.240924e-02
log_SO2  -4.615482e-17 -1.211723e-01  5.240924e-02  1.000000e+00</code></pre>
</div>
</div>
<p>Though a simple correlation coefficient test doesn’t guarantee their independence, a low correlation coefficient might indicates that they would satisfy the assumption.</p>
</section>
<section id="zero-mean" class="level2">
<h2 class="anchored" data-anchor-id="zero-mean">Zero Mean</h2>
<p>The errors should be averaged at 0 for any given X. The plot below shows that given <em>Precip, NonWhite,</em> and <em>log(SO2)</em> the residuals are centered around 0. Thus, it satisfy this assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(X_resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="homoscedastic" class="level2">
<h2 class="anchored" data-anchor-id="homoscedastic">Homoscedastic</h2>
<p>The variance of the errors should also be constant for any given X. This assumption can be evaluated by plotting the fitted values against the residuals or by using statistical test such as Breusch-Pagan test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>fit_resid <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit =</span> dummy_unscaled<span class="sc">$</span>fitted.values,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">resid =</span> dummy_unscaled<span class="sc">$</span>residuals</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fit_resid, <span class="fu">aes</span>(<span class="at">x =</span> fit, <span class="at">y =</span> resid)) <span class="sc">+</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">'blue'</span>)<span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> <span class="st">'y ~ x'</span>, <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Fitted Values'</span>, <span class="at">y =</span> <span class="st">'Residuals'</span>, <span class="at">title =</span> <span class="st">'Homoscedastic Test'</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">'dashed'</span>, <span class="at">color =</span> <span class="st">'black'</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(dummy_unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  dummy_unscaled
BP = 22.66, df = 31, p-value = 0.8612</code></pre>
</div>
</div>
<p>With a null hypothesis of “the residuals are homoscedastic” and the Breusch-Pagan test obtained a p-value of 0.8612, We do not reject the null hypothesis. Therefore, the model doesn’t violate the homoscedasticity assumption.</p>
</section>
<section id="autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="autocorrelation">Autocorrelation</h2>
<p>The correlation between two <em>X</em> values X<sub>i</sub> and X<sub>j</sub> (i ≠ j) should be zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dwtest</span>(dummy_unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  dummy_unscaled
DW = 1.9599, p-value = 0.4104
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>The Durbin-Watson test is one of the most commonly used test for detecting autocorrelation. The results indicate that there is no autocorrelation in this model.</p>
</section>
<section id="number-of-observations-greater-than-parameters" class="level2">
<h2 class="anchored" data-anchor-id="number-of-observations-greater-than-parameters">Number of Observations Greater than Parameters</h2>
<p>This assumption is necessary because if the number of observations <em>n</em> is less than the number of parameters <em>p</em>, the model becomes mathematically under determined. In this case, <em>X<sup>T</sup> X</em> is singular, leading to non-unique solutions, perfect overfitting, and undefined statistical tests such as standard errors, t-values, and p-values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df2) <span class="sc">&gt;</span> <span class="fu">length</span>(dummy_unscaled<span class="sc">$</span>coefficients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="sufficient-variation" class="level2">
<h2 class="anchored" data-anchor-id="sufficient-variation">Sufficient Variation</h2>
<p>The <em>X</em> values in a given sample must not all be the same. In the EDA section I have provided graphs that show the variability in <em>X</em>’s values, which in the final model <em>X</em> is <em>Precip, NonWhite,</em> and <em>SO2</em>. Therefore, this assumption is met by this model.</p>
<p>This assumption would be violated if <em>NOX</em> were included since it doesn’t have sufficient variation in its value.</p>
</section>
<section id="multicollinearity" class="level2">
<h2 class="anchored" data-anchor-id="multicollinearity">Multicollinearity</h2>
<p>The presence of multicollinearity might affect the stability and the precision of the estimation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(dummy_unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               GVIF Df GVIF^(1/(2*Df))
Precip    19.623029  1        4.429789
NonWhite  11.203163  1        3.347113
log(SO2)   5.844641  1        2.417569
Location 654.355380 28        1.122748</code></pre>
</div>
</div>
<p>The rule of thumb for interpreting VIF (Adjusted GVIF in this case) is that if the value is less than the threshold of 10, it can be concluded that there is no multicollinearity. Hence, this model meets the assumption of no multicollinearity.</p>
<p>Note: There might be a difference when the covariates are all numeric (use VIF) or combination of numeric and categorical (use GVIF<sup>1/(2*df)</sup> /Adjusted GVIF)</p>
</section>
<section id="correctly-specified" class="level2">
<h2 class="anchored" data-anchor-id="correctly-specified">Correctly Specified</h2>
<p>One of the assumption of linear regression is that there is no specification bias. RESET test is a common test to evaluate whether the model is correctly specified. RESET test present a null hypothesis of model is not misspecified.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(dummy_unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  dummy_unscaled
RESET = 0.59487, df1 = 2, df2 = 26, p-value = 0.559</code></pre>
</div>
</div>
<p>The result indicates that the null hypothesis is not rejected, thus the model is correctly specified.</p>
<p>Nevertheless, this assumption should not be decided only on the test, but on good economic sense or domain knowledge as well. For example, the Educ variable was dropped from the final model because of its misleading estimation effect, which was identified based on domain knowledge.</p>
<p>In the final model, all variables clearly make logical sense. Therefore, this assumption is satisfied.</p>
</section>
<section id="normally-distributed-error" class="level2">
<h2 class="anchored" data-anchor-id="normally-distributed-error">Normally Distributed Error</h2>
<p>Lastly, it is assumed that the errors in a linear regression model are normally distributed. However, this assumption is crucial for statistical inference, not for estimating/fitting the model as I have done here. Furthermore, since this dataset contains an adequate number of observations (60), this assumption could be justified by the Central Limit Theorem (CLT).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dummy_unscaled<span class="sc">$</span>residuals, <span class="at">freq =</span> F, <span class="at">col =</span> <span class="st">'lightblue'</span>, <span class="at">breaks =</span> <span class="dv">13</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(dummy_unscaled<span class="sc">$</span>residuals), <span class="at">col =</span> <span class="st">'blue'</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Air_Pollution_on_Mortality_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dummy_unscaled<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  dummy_unscaled$residuals
W = 0.91378, p-value = 0.0004347</code></pre>
</div>
</div>
<p>The results from the Shapiro–Wilk test indicate that the errors do not follow a normal distribution. Nonetheless, as stated earlier, this assumption is not critical for the purpose of model fitting in this case and the model still valid because of the sufficient number of observations.</p>
</section>
</section>
<section id="is-it-a-good-fit" class="level1">
<h1>Is It a Good Fit?</h1>
<p>In conclusion, the final mode <em>dummy model</em> is generally a good fit because it satisfies all the assumptions. It also generates an R-squared of 0.7421, which is high enough to be considered a good representation. Furthermore, I think that all the included variables, though not all are statistically significant, have an impact on <em>Mort</em>. We might conclude that <em>Precip, NonWhite,</em> and <em>SO2</em> are causally related to the mortality rate, as this aligns with logical reasoning. However, to fully establish their causal effect on <em>Mort</em>, a more specific research design and advanced domain knowledge would be required.</p>
<p>I think that’s all for this analysis. I remain open to any critiques or recommendations regarding my analysis, as well as discussions about better approaches, updated models, and broader insights on how to integrate statistical conclusions with domain knowledge. Thank You!</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>